Feature/sqlite
Nekobitlz/OPD-2020 pull request #1
Opened 2020-03-12 16:49 UTC by Suagami

2020-03-13 13:15 UTC, Suagami commented
запись данных в csv пришлось писать вручную, так как в SQLite нет селекта в файл, как в MySQL

2020-03-13 23:09 UTC, Nekobitlz requested changes

2020-03-13 23:09 UTC, Nekobitlz commented on src/main/java/database/DatabaseImpl.java
> +                BufferedWriter writer = new BufferedWriter(new FileWriter(file, true));
Тут можно заменить на try-with-resources, тогда не придётся писать writer.close(), потому что BufferedWriter реализует интерфейс AutoClosable 
`                try (BufferedWriter writer = new BufferedWriter(new FileWriter(file, true))) {
`

2020-03-13 23:09 UTC, Nekobitlz commented on src/main/java/database/DatabaseImpl.java
> +                ResultSet rset = statement.executeQuery(query);
Я затупил и забыл, что ResultSet тоже надо закрывать после того как мы данные положили, у нас тут сейчас везде утечки могут возникнуть, его тоже нужно оборачивать в try-with-resources
`try (ResultSet rset = statement.executeQuery(query)) {`

Но я это сам исправлю, после того как твой код замерджу, потому что в своих методах я его тоже просто так писал.

2020-03-13 23:09 UTC, Nekobitlz commented on src/main/java/database/DatabaseImpl.java
> +    public boolean exportDataToCSV(String filepath) {
Я бы этот метод разбил на два на самом деле, потому что он сейчас: первое - достаёт из бд данные, второе - записывает их в файл. Это нарушает single responsibility principle. Но это так, на будущее, сейчас пофигу, не трать на это время, мы всё равно вряд ли будем этот метод менять.

2020-03-13 23:09 UTC, Nekobitlz commented on src/main/java/database/DatabaseImpl.java
> +        String query = "SELECT * FROM websites WHERE company_id=(SELECT website_id FROM words WHERE word='"+word+"')";
У тебя тут всё хорошо, менять ничего не надо. 

Я просто сделал ещё несколько вариантов этого запроса, по-моему по времени они все одинаковые. Сохраню тут чисто для себя.

`       String query = "SELECT websites.* FROM websites LEFT JOIN words ON websites.company_id=words.website_id WHERE words.word='"+word+"'";`

`  String query = "SELECT websites.* FROM websites, words WHERE websites.company_id=words.website_id AND words.word='"+word+"'";`

2020-03-13 23:09 UTC, Nekobitlz commented on src/main/java/database/DatabaseImpl.java
> +        Word word = null;
Лучше в случае успеха возвращать `return new Word(website_id, wordStr);` , а в случае эксепшена `return null;` Тогда не придётся хранить лишний объект в куче.

2020-03-13 23:09 UTC, Nekobitlz commented on src/test/java/DatabaseTest.java
> +            File file = new File(csvpath);
Опять же тут надо использовать try-with-resources, потому что тут у тебя опять возникает утечка памяти, т.к. ты FileReader закрыла, а BufferedReader - нет. 

```
File file = new File(csvpath);
        try (FileReader fr = new FileReader(file)) {
            try (BufferedReader br = new BufferedReader(fr)) {
```

2020-03-13 23:09 UTC, Nekobitlz commented on src/main/java/database/Database.java
> +     * Returns a list containing all the websites from the "websites" table
Поменяй в комментариях list на set тоже. Хотя на самом деле нашу документацию вряд ли кто-то читать будет :D

2020-03-14 09:44 UTC, Suagami commented on src/main/java/database/DatabaseImpl.java
> +                ResultSet rset = statement.executeQuery(query);
Сама исправила, мне не сложно)

2020-03-14 09:45 UTC, Suagami commented on src/main/java/database/DatabaseImpl.java
> +    public boolean exportDataToCSV(String filepath) {
Разбила, правда пришлось добавить класс для триплов, чтобы было проще хранить записи (хотя это скорее всего неправильно)

2020-03-14 11:59 UTC, Nekobitlz requested changes
Вот тут чуть-чуть исправь пожалуйста, в остальном всё норм

2020-03-14 11:59 UTC, Nekobitlz commented on src/main/java/database/DatabaseImpl.java
> +            List<Triple<Integer, Integer, String>> list = getWordsData();
Ну да, тут трипл тут лишний, потому что у нас уже есть класс Word, который и содержит все эти поля, я бы лучше просто добавил туда поле id

2020-03-14 11:59 UTC, Nekobitlz commented on src/main/java/CSVParser.java
> +            Logger log = Logger.getLogger(CSVParser.class.getName());
Это лучше убери из этого пулл реквеста и кинь Андрею в репозиторий отдельно, потому что у нас ветка с базой данных и она может не замерджиться, из-за того, что тут меняются два класса парсера

2020-03-14 21:14 UTC, merged